# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    routing_loader: false
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
